build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.20"
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.20"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.20"
  i386: "ghcr.io/home-assistant/i386-base-python:3.12-alpine3.20"
labels:
  org.opencontainers.image.title: "MindHome"
  org.opencontainers.image.description: "KI-basierte Smart Home Automatisierung"
  org.opencontainers.image.version: "0.7.18"
  org.opencontainers.image.source: "https://github.com/Goifal/mindhome"
  org.opencontainers.image.licenses: "MIT"
